CollectionHub/Models/CollectionViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace CollectionHub.Models
{
    public class CollectionViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please choose a theme.")]
        public string? Theme { get; set; }

        [Required(ErrorMessage = "Please enter a collection name.")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Please enter a description.")]
        public string? Description { get; set; }

        public string? ImageLink { get; set; }

        public IFormFile? File { get; set; }

        public List<SelectListItem>? Themes { get; set; }

        public List<ItemViewModel> Items { get; set; }

        public List<SelectListItem> ItemsDataTypes { get; set; }

        public List<string> AllHeaders { get; set; }
    }
}

CollectionHub/Models/ViewModels/CollectionViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace CollectionHub.Models.ViewModels
{
    public class CollectionViewModel
    {
        public long Id { get; set; }

        [Required(ErrorMessage = "Please choose a category.")]
        public string? Category { get; set; }

        [Required(ErrorMessage = "Please enter a collection name.")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Please enter a description.")]
        public string? Description { get; set; }

        public string? ImageUrl { get; set; }

        public IFormFile? File { get; set; }

        public List<SelectListItem>? Categories { get; set; }

        public List<ItemViewModel>? Items { get; set; }

        public List<SelectListItem>? ItemsDataTypes { get; set; }

        public Dictionary<string, string>? AllHeaders { get; set; }
    }
}

CollectionHub/Controllers/CollectionController.cs
using CollectionHub.Domain;
using CollectionHub.Domain.Converters;
using CollectionHub.Models.ViewModels;
using CollectionHub.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CollectionHub.Controllers
{
    public class CollectionController : Controller
    {
        private readonly ICollectionService _collectionService;

        public CollectionController(ICollectionService collectionService) => _collectionService = collectionService;

        [HttpGet]
        public async Task<IActionResult> LargestCollections() => View(await _collectionService.GetLargestCollections());

        [HttpGet]
        public async Task<IActionResult> GetCollectionForRead(int id) => View(await _collectionService.GetCollectionForRead(id));

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> MyCollections() => View(await _collectionService.GetUserCollections(this.GetUserNameFromContext()));

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> CreateCollection()
        {
            var viewModel = await _collectionService.GetEmptyCollectionViewModel();

            if (TempData.TryGetValue("ImageUrl", out var imagePath) && imagePath != null)
            {
                viewModel.ImageUrl = (string)imagePath;
            }

            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateCollection(CollectionViewModel collectionViewModel)
        {
            if (ModelState.IsValid)
            {
                await _collectionService.CreateCollection(collectionViewModel, this.GetUserNameFromContext());

                return RedirectToAction("MyCollections");
            }

            return View(await _collectionService.GetEmptyCollectionViewModel());
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> GetCollection(int id)
        {
            var errorMessage = TempData["ErrorMessage"] as string;

            if (!string.IsNullOrEmpty(errorMessage))
            {
                ModelState.AddModelError("error", errorMessage);
            }

            return View(await _collectionService.GetUserCollection(this.GetUserNameFromContext(), id));
        }

        [Authorize]
        public async Task<IActionResult> ExportCSV(long collectionId)
        {
            var collection = await _collectionService.GetUserCollection(this.GetUserNameFromContext(), collectionId);

            return File(collection.ToCsvBytes(), "text/csv", $"{collection.Name}.csv");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddCollectionItemField(long collectionId, string type, string name)
        {
            if (ModelState.IsValid)
            {
                var result = await _collectionService.CreateCollectionItemField(this.GetUserNameFromContext(), collectionId, type.ToDataType(), name);
                if (!result)
                {
                    TempData["ErrorMessage"] = ErrorMessageManager.FieldLimit;
                }
                return RedirectToAction("GetCollection", new { id = collectionId });
            }

            TempData["ErrorMessage"] = ErrorMessageManager.TypeSelection;

            return RedirectToAction("GetCollection", new { id = collectionId });
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> DeleteCollection(long id)
        {
            await _collectionService.DeleteCollection(this.GetUserNameFromContext(), id);

            return RedirectToAction("MyCollections");
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditCollection(long id)
        {
            var collection = await _collectionService.GetUserCollection(this.GetUserNameFromContext(), id);

            if (TempData.TryGetValue("ImageUrl", out var imagePath) && imagePath != null)
            {
                collection.ImageUrl = (string)imagePath;
            }

            return View(collection);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditCollection(CollectionViewModel collectionViewModel)
        {
            if (ModelState.IsValid)
            {
                await _collectionService.EditCollection(this.GetUserNameFromContext(), collectionViewModel);

                return RedirectToAction("MyCollections");
            }

            return View(await _collectionService.GetEmptyCollectionViewModel());
        }
    }
}

CollectionHub/Controllers/ImageController.cs
using CollectionHub.Models.ViewModels;
using CollectionHub.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CollectionHub.Controllers
{
    public class ImageController : Controller
    {
        private readonly IImageService _imageService;

        public ImageController(IImageService imageService) => _imageService = imageService;

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UploadImage(CollectionViewModel collectionViewModel)
        {
            TempData["ImageUrl"] = _imageService.UploadImageToAzureAndGiveImageLink(collectionViewModel.File);

            return RedirectToAction("CreateCollection", "Collection");
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateImage(CollectionViewModel collectionViewModel, long collectionId)
        {
            TempData["ImageUrl"] = _imageService.UploadImageToAzureAndGiveImageLink(collectionViewModel.File);

            return RedirectToAction("EditCollection", "Collection", new { id = collectionId });
        }
    }
}

CollectionHub/Controllers/ItemController.cs
using CollectionHub.Domain;
using CollectionHub.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CollectionHub.Controllers
{
    public class ItemController : Controller
    {
        private readonly ICollectionService _collectionService;

        private readonly IItemService _itemService;

        public ItemController(ICollectionService collectionService, IItemService itemService)
        {
            _collectionService = collectionService;
            _itemService = itemService;
        }

        [HttpGet]
        public async Task<IActionResult> SearchItems(string query) => View(await _itemService.SearchItems(query));

        [HttpGet]
        public async Task<IActionResult> GetItem(long itemId, long collectionId) => View(await _itemService.GetItem(itemId, collectionId));

        [HttpGet]
        public async Task<IActionResult> RecentlyAdded() => View(await _itemService.GetRecentlyAddedItemsForRead());

        [HttpPost]
        public async Task<IActionResult> AddComment(string text, long itemId, long collectionId)
        {
            if (HttpContext.User.Identity == null || !HttpContext.User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            await _itemService.AddComment(this.GetUserNameFromContext(), itemId, text);

            return NoContent();
        }

        [HttpGet]
        public async Task<IActionResult> PressLike(long itemId, long collectionId)
        {
            if (HttpContext.User.Identity == null || !HttpContext.User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            await _itemService.ProcessLikeItem(this.GetUserNameFromContext(), itemId);

            return RedirectToAction("GetItem", new { itemId, collectionId });
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> CreateItem(long collectionId) => View(await _collectionService.GetUserCollection(this.GetUserNameFromContext(), collectionId));

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateItem(IFormCollection formCollection)
        {
            var collectionId = await _itemService.CreateItem(this.GetUserNameFromContext(), formCollection);

            return RedirectToAction("GetCollection", "Collection", new { id = collectionId });
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> EditItem(int collectionId, int selectedItemId)
        {
            if (ModelState.IsValid)
            {
                return View(await _itemService.GetItem(selectedItemId, collectionId));
            }

            TempData["ErrorMessage"] = ErrorMessageManager.ItemSelection;

            return RedirectToAction("GetCollection", "Collection", new { id = collectionId });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditItem(IFormCollection formCollection)
        {
            var collectionId = await _itemService.EditItem(this.GetUserNameFromContext(), formCollection);

            return RedirectToAction("GetCollection", "Collection", new { id = collectionId });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(int collectionId, int selectedItemId)
        {
            if (ModelState.IsValid)
            {
                await _itemService.DeleteItem(this.GetUserNameFromContext(), selectedItemId);

                return RedirectToAction("GetCollection", "Collection", new { id = collectionId });
            }

            TempData["ErrorMessage"] = ErrorMessageManager.NoItemSelected;

            return RedirectToAction("GetCollection", "Collection", new { id = collectionId });
        }
    }
}

CollectionHub/Views/Collection/CreateCollection.cshtml
@model CollectionHub.Models.ViewModels.CollectionViewModel
@{
    ViewData["Title"] = "Create collection";
}

<div class="row justify-content-center mb-3">
    <div class="col-7">
        <h2>@Localizer["createCollection"]</h2>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-12 col-sm-6 col-md-3 order-2 order-sm-1 order-md-1">
        <form id="imageForm" method="post" action="@Url.Action("UploadImage", "Image")" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            @if (!string.IsNullOrEmpty(Model.ImageUrl))
            {
                <img src="@Url.Content(Model.ImageUrl)" alt="Uploaded Image" class="uploaded-image" />
            }
            else
            {
                <label for="fileInput">
                    <img src="~/AddImage.png" alt="Add image" class="clicked-image" />
                </label>
            }
            <input type="file" id="fileInput" name="File" style="display: none;" onchange="submitForm()" />

            <button type="submit" id="submitButton" style="display: none;"></button>
        </form>
    </div>
    <div class="col-12 col-sm-6 col-md-4 order-1 order-sm-2 order-md-2">
        <form id="createCollectionForm" method="post" asp-action="CreateCollection">

            <input type="hidden" asp-for="Categories" value="@Model.Categories" />

            <div class="form-group mb-3">
                <label asp-for="Category">@Localizer["category"]</label>
                <select class="form-select" asp-for="Category" asp-items="@Model.Categories" required>
                    <option value="" selected>@Localizer["chooseCategory"]</option>
                </select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Name">@Localizer["name"]</label>
                <input asp-for="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Description">@Localizer["description"]</label>
                <textarea asp-for="Description" class="form-control" rows="4" cols="30" required></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <button type="submit" class="w-100 btn btn-lg btn-primary" onclick="prepareFormData()">@Localizer["create"]</button>
        </form>
    </div>
</div>

<script>
    function submitForm() {
        document.getElementById('submitButton').click();
    }

    function prepareFormData() {
        var imageFileDetails = "@Model.ImageUrl";

        $("#createCollectionForm").append('<input type="hidden" name="ImageUrl" value="' + imageFileDetails + '">');
    }
</script>

CollectionHub/Views/Collection/EditCollection.cshtml
@model CollectionHub.Models.ViewModels.CollectionViewModel
@{
    ViewData["Title"] = "Edit collection";
}

<div class="row justify-content-center mb-3">
    <div class="col-7">
        <h2>@Localizer["createCollection"]</h2>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-12 col-sm-6 col-md-3">
        <form id="imageForm" method="post" action="@Url.Action("UpdateImage", "Image")" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            @if (!string.IsNullOrEmpty(Model.ImageUrl))
            {
                <label for="fileInput">
                    <img src="@Url.Content(Model.ImageUrl)" alt="Uploaded Image" class="clicked-image" />
                </label>
            }
            else
            {
                <label for="fileInput">
                    <img src="~/AddImage.png" alt="Add image" class="clicked-image" />
                </label>
            }
            <input type="hidden" id="collectionId" name="CollectionId" value="@Model.Id" />

            <input type="file" id="fileInput" name="File" style="display: none;" onchange="submitForm()" />

            <button type="submit" id="submitButton" style="display: none;"></button>
        </form>
    </div>
    <div class="col-12 col-sm-6 col-md-4">
        <form id="createCollectionForm" method="post" asp-action="EditCollection">

            <div class="form-group mb-3">
                <label asp-for="Category">@Localizer["category"]</label>
                <select class="form-select" asp-for="Category" asp-items="@Model.Categories">
                    <option value="" selected>@Localizer["chooseCategory"]</option>
                </select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Name">@Localizer["name"]</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Description">@Localizer["description"]</label>
                <textarea asp-for="Description" class="form-control" rows="4" cols="30">@Model.Description</textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <button type="submit" class="w-100 btn btn-lg btn-primary" onclick="prepareFormData()">@Localizer["edit"]</button>
        </form>
    </div>
</div>

<script>
    function submitForm() {
        document.getElementById('submitButton').click();
    }

    function prepareFormData() {
        var imageFileDetails = "@Model.ImageUrl";

        $("#createCollectionForm").append('<input type="hidden" name="ImageUrl" value="' + imageFileDetails + '">');
    }
</script>

CollectionHub/Views/Collection/GetCollection.cshtml
@model CollectionHub.Models.ViewModels.CollectionViewModel

@{
    ViewData["Title"] = "Collection";
}

@if (ViewData.ModelState.Values.Any(v => v.Errors.Count > 0))
{
    <div class="alert alert-danger d-flex align-items-center justify-content-center" role="alert">
        @Html.ValidationMessage("error")
    </div>
}

<div class="row">
    <div class="col-md-6">
        <h2 class="text-left text-uppercase mb-4">@Model.Name</h2>
        @{
            var renderer = new MarkdownSharp.Markdown();
            string htmlDescription = renderer.Transform(Model.Description);
        }

        <div>
            @Html.Raw(htmlDescription)
        </div>
    </div>
    <div class="col-md-4 offset-md-1">
        <h2 class="text-uppercase mb-4">@Localizer["addColumn"]</h2>
        <form method="post" asp-action="AddCollectionItemField">
            <input type="hidden" name="collectionId" value="@Model.Id" />

            <div class="form-group mb-3">
                <label>Type</label>
                <select class="form-select" name="type" asp-items="@Model.ItemsDataTypes">
                    <option value="" selected>@Localizer["chooseType"]</option>
                </select>
            </div>

            <div class="form-group mb-3">
                <label>@Localizer["name"]</label>
                <input type="text" name="name" class="form-control" />
            </div>

            <button type="submit" class="w-100 btn btn-lg btn-primary">@Localizer["add"]</button>
        </form>
    </div>

    <div class="col-md-4 d-flex">
        <a class="btn btn-primary rounded-pill me-2" href="@Url.Action("CreateItem", "Item", new { collectionId = Model.Id})">@Localizer["create"]</a>

        <form method="get" asp-controller="Item" asp-action="EditItem">
            <input type="hidden" name="collectionId" value="@Model.Id" />
            <input type="hidden" name="selectedItemId" id="editSelectedItemId" />
            <button type="submit" class="btn btn-secondary rounded-pill me-2">@Localizer["edit"]</button>
        </form>

        <form method="post" asp-controller="Item" asp-action="DeleteItem">
            <input type="hidden" name="collectionId" value="@Model.Id" />
            <input type="hidden" name="selectedItemId" id="deleteSelectedItemId" />
            <button type="submit" class="btn btn-danger rounded-pill me-2">@Localizer["delete"]</button>
        </form>

        <a class="btn btn-success rounded-pill" href="@Url.Action("ExportCSV", "Collection", new { collectionId = Model.Id})">@Localizer["export"]</a>
    </div>
</div>

@if (Model.AllHeaders != null)
{
    <div class="table-responsive mt-2">
        <table class="table">
            <thead>
                <tr>
                    <th><input type="hidden" /></th>
                    <th scope="col">#</th>
                    @foreach (var header in Model.AllHeaders)
                    {
                        <th scope="col">@header.Value</th>
                    }
                </tr>
            </thead>
            <tbody>
                @if (Model.Items != null)
                {
                    for (int i = 0; i < Model.Items.Count; i++)
                    {
                        var rowData = Model.Items[i];

                        <tr>
                            <td><input type="radio" class="item-radio" name="selectItem" data-item-id="@rowData[0]" /></td>
                            <td>@(i + 1)</td>
                            @for (int j = 1; j < rowData.Count; j++)
                            {
                                if (j == 1)
                                {
                                    <td>
                                        <a href="@Url.Action("GetItem", "Item", new { itemId = rowData[0], collectionId = Model.Id })"
                                           class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">@rowData[j]</a>
                                    </td>
                                }
                                else
                                {
                                    <td>@(rowData[j].Length > 50 ? rowData[j].Substring(0, 20) + "..." : rowData[j])</td>
                                }
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
}

@section scripts {
    <script>
        $(document).ready(function () {
            $('.table').DataTable();

            $(".item-radio").change(function () {
                var selectedId = $(".item-radio:checked").data("item-id");
                $("#editSelectedItemId").val(selectedId);
                $("#deleteSelectedItemId").val(selectedId);
            });
        });
    </script>
}

CollectionHub/Views/Collection/GetCollectionForRead.cshtml
@model CollectionHub.Models.ViewModels.CollectionViewModel

@{
    ViewData["Title"] = "Collection";
}

<div class="row">
    <div class="col-md-6">
        <h2 class="text-left text-uppercase mb-4">@Model.Name</h2>
        @{
            var renderer = new MarkdownSharp.Markdown();
            string htmlDescription = renderer.Transform(Model.Description);
        }

        <div>
            @Html.Raw(htmlDescription)
        </div>
    </div> 
    <div class="col-md-6 d-flex align-items-center justify-content-center">
        @if (Model.ImageUrl == null)
        {
            <img src="~/NoImage.png" class="card-img-left uploaded-image" alt="No image">
        }
        else
        {
            <img src="@Model.ImageUrl" class="card-img-left uploaded-image" alt="Collection Image">
        }
    </div>
</div>

@if (Model.AllHeaders != null)
{
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    @foreach (var header in Model.AllHeaders)
                    {
                        <th scope="col">@header.Value</th>
                    }
                </tr>
            </thead>
            <tbody>
                @if (Model.Items != null)
                {
                    for (int i = 0; i < Model.Items.Count; i++)
                    {
                        var rowData = Model.Items[i];

                        <tr>
                            <td>@(i + 1)</td>
                            @for (int j = 1; j < rowData.Count; j++)
                            {
                                if (j == 1)
                                {
                                    <td>
                                        <a href="@Url.Action("GetItem", "Item", new { itemId = rowData[0], collectionId = Model.Id })"
                                           class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">@rowData[j]</a>
                                    </td>
                                }
                                else
                                {
                                    <td>@(rowData[j].Length > 50 ? rowData[j].Substring(0, 20) + "..." : rowData[j])</td>
                                }
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
}

@section scripts {
    <script>
        $(document).ready(function () {
            $('.table').DataTable();
        });
    </script>
}

CollectionHub/Views/Collection/LargestCollections.cshtml
@using CollectionHub.Models.ViewModels
@model List<CollectionViewModel>

@{
    ViewData["Title"] = "Largest collections";
}

<div class="row">
    <div class="col-md-12 mb-4">
        <h2>@Localizer["largest"]</h2>
    </div>
    @if (Model.Count == 0)
    {
        <p class="mt-4">@Localizer["noCollections"]</p>
    }
    else
    {
        @foreach (var collection in Model)
        {
            <div class="col-md-6 col-12 mb-4">
                <div class="card flex-row border-0">
                    @if (collection.ImageUrl == null)
                    {
                        <img src="~/NoImage.png" class="card-img-left uploaded-image" alt="No image">
                    }
                    else
                    {
                        <img src="@collection.ImageUrl" class="card-img-left uploaded-image" alt="Collection Image">
                    }
                    <div class="card-body">
                        <h5 class="card-title h4-sm">@collection.Name</h5>
                        <p class="card-text">
                            @{
                                var htmlDescription = string.Empty;
                                if (@collection.Description != null)
                                {
                                    var truncatedDescription = @collection.Description.Length > 250 ? @collection.Description.Substring(0, 200) + "..." : @collection.Description;
                                    var renderer = new MarkdownSharp.Markdown();
                                    htmlDescription = renderer.Transform(truncatedDescription);
                                }
                            }

                            <div>
                                @Html.Raw(htmlDescription)
                            </div>
                        </p>
                        <a href="@Url.Action("GetCollectionForRead", "Collection", new { id = collection.Id })" class="stretched-link"></a>
                    </div>
                </div>
            </div>
        }
    }
</div>

CollectionHub/Views/Collection/MyCollections.cshtml
@model List<CollectionHub.Models.ViewModels.CollectionViewModel>

@{
    ViewData["Title"] = "My collections";
}

<div class="row">
    <div class="col-md-6 mb-4">
        <h2>@Localizer["myCollections"]</h2>
    </div>
    <div class="col-md-6 text-md-end">
        <a class="btn btn-primary rounded-pill" href="@Url.Action("CreateCollection", "Collection")">
            @Localizer["createCollections"]
        </a>
    </div>
    @if (Model.Count == 0)
    {
        <p class="mt-4">@Localizer["explanation"]</p>
    }
    else
    {
        @foreach (var collection in Model)
        {
            <div class="col-md-6 col-12">
                <div class="card flex-row border-0">
                    @if (collection.ImageUrl == null)
                    {
                        <img src="~/NoImage.png" class="card-img-left uploaded-image" alt="No image">
                    }
                    else
                    {
                        <img src="@collection.ImageUrl" class="card-img-left uploaded-image" alt="Collection Image">
                    }
                    <div class="card-body">
                        <h5 class="card-title h4-sm">@collection.Name</h5>
                        <p class="card-text">
                            @{
                                var htmlDescription = string.Empty;
                                if (@collection.Description != null)
                                {
                                    var truncatedDescription = @collection.Description.Length > 250 ? @collection.Description.Substring(0, 200) + "..." : @collection.Description;
                                    var renderer = new MarkdownSharp.Markdown();
                                    htmlDescription = renderer.Transform(truncatedDescription);
                                }
                            }

                            <div>
                                @Html.Raw(htmlDescription)
                            </div>
                        </p>
                        <a href="@Url.Action("GetCollection", "Collection", new { id = collection.Id })" class="stretched-link"></a>
                    </div>
                </div>
                <div class="d-flex flex-row-reverse mb-1">
                    <a class="p-2 text-secondary a-custom-hover" onclick="confirmDelete('@Url.Action("DeleteCollection", "Collection", new { id = collection.Id })')">
                        <i class="fa-regular fa-trash-can"></i>
                    </a>
                    <a class="p-2 text-secondary a-custom-hover" href="@Url.Action("EditCollection", "Collection", new { id = collection.Id })">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>
                </div>
            </div>
        }
    }
</div>

<script>
    function confirmDelete(deleteUrl) {
        var result = confirm("Are you sure you want to delete?");
        if (result) {
            window.location.href = deleteUrl;
        }
    }
</script>